app = "goldbot"

[build]
  builder = "dockerfile"

[env]
  TELEGRAM_TOKEN = "YOUR_BOT_API_TOKEN"

[http_service]
  internal_port = 8080
  force_https = true

[deploy]
  release_command = "python main.py"

[mounts]
  source = "data"
  destination = "/app"